


lang: es-EC

title: "Jaime Anchundia"

description: "Bienevenidos al Blog de Jaime Anchundia"

baseurl: ""

google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Inicio
    url: /   
  - text: Sobre Mi
  Hola, mi nombre es Jaime Francisco Anchundia Magallanes, soy  de  nacionalidad Ecuatoriana,  tengo  19 años,  nacido en Guayaquil el 1 de Julio del 2001. Me considero una persona responsable, atenta, amable,  me  gusta ayudar a las personas, me encantan los perritos.
    url: imagen/ jaime.jpg
  - text: Mi Educacion    
  Mis estudios los inicié desde los 3 años en un establecimiento llamado Parvulitos de Jesús , entré a primaria  en la escuela José Mejía Lequerica, a los 11 años ingresé al colegio DR. Juan Modesto Carbo Noboa cerca de mi hogar donde obtuve mi título de bachiller en Contabilidad y Administración.
# The shortname for your Disqus site to enable comments.
disqus: Jaime Anchundia

# Includes an icon in the footer for each username you enter 
footer-links: 
email: jaimeanchundia0107@gmail.com
facebook: https://www.facebook.com/profile.php?id=100025394716811
instagram: https://www.instagram.com/Jaimeanchundia01/

# Colors 
accent_color: '#207c2b'

# Site footer
footer:
  content: "&copy; Saltos's Blog"
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
