


lang: es-EC

title: "Jaime Anchundia"

description: "Bienevenidos al Blog de Jaime Anchundia"

baseurl: ""

google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Inicio
    url: /
  - text: Sobre Mi
    url: /about
  - text: Mi Educacion
    url: /Educacion
  - text: Archivos
    url: /tags

# The shortname for your Disqus site to enable comments.
disqus: Jaime Anchundia

# Colors
accent_color: '#207c2b'

# Site footer
footer:
  content: "&copy; Saltos's Blog"
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
